site_name: Chango Private
site_url: https://cloudcheflabs.github.io/chango-private-docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: lime
  logo: images/chango-logo.png
  favicon: images/chango-logo.png


nav:
  - "What is Chango Private?":
      - "What is Chango Private?": intro/intro.md
  - "Getting Started":
      - "Install Chango Admin": install/install-admin.md
      - "Install Chango Components": install/install-component.md
      - "Run First Trino Query": install/run-first-ctas.md
  - "Features":
      - "Storage Security": features/rbac.md
      - "Data Ingestion": features/ingestion.md
      - "Realtime Analytics": features/realtime.md
      - "Trino Gateway": features/trino-gw.md
  - "User Guide":
      - "Get Chango Credential": user-guide/cred.md
      - "Get S3 Credential": user-guide/s3-cred.md
      - "Send Streaming Events": user-guide/streaming.md
      - "Upload Files": user-guide/upload.md
      - "Upload Excel": user-guide/upload-excel.md
      - "Connect to Chango Trino Gateway with Trino Clients": user-guide/connect-trino-gw.md
      - "Create Iceberg REST Catalog in Spark": user-guide/rest-in-spark.md
      - "Run dbt Model": user-guide/dbt.md
      - "Create Azkaban Project using CLI": user-guide/azkaban-cli.md
      - "Run Spark Jobs with Azkaban": user-guide/spark-azkaban.md
      - "Create Kafka Topic": user-guide/kafka-topic.md
      - "Configure Schema Registry URL": user-guide/schema-reg.md
      - "Reading Log Files Using Chango Log": user-guide/chango-log.md
      - "Change Data Capture Using Chango CDC": user-guide/chango-cdc.md
  - "Components":
     - "Components": components/components.md


extra:
  generator: false
  version:
    provider: mike
    default: 2.1.0



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  © <script>document.write(new Date().getFullYear())</script> Cloud Chef Labs, Inc. All rights reserved. <a href="mailto:admin@cloudchef-labs.com">admin@cloudchef-labs.com</a>