site_name: Chango Private
site_url: https://cloudcheflabs.github.io/chango-private-docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: lime
  logo: images/chango-logo.png


#nav:
#  - Home: index.md
#  - "User Guide":
#     - "Test 1": test/page2.md
#     - "Test 3": test/page3.md
#  - "Bug Tracker": "/bugs/"



extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/
  version:
    provider: mike
    default: latest



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>