site_name: Chango Private
site_url: https://cloudcheflabs.github.io/chango-private-docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: lime
  logo: images/chango-logo.png
  favicon: images/chango-logo.png


nav:
  - "Getting Started":
      - "Install Chango Admin": install/install-admin.md
      - "Install Chango Components": install/install-component.md
      - "Run First Trino Query": install/run-first-ctas.md
  - "User Guide":
      - "Send Streaming Events": ingest/streaming.md
  - "Introduction":
     - "Introduction": intro/intro.md
  - "Features":
     - "Chango Private Storage Security": features/rbac.md
     - "Chango Private Streaming": features/streaming.md
     - "Chango Private Data Ingestion": features/ingestion.md
     - "Chango Private Trino Gateway": features/trino-gw.md
  - "Components":
     - "Components": components/components.md


extra:
  generator: false
  version:
    provider: mike
    default: 2.1.0



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  © <script>document.write(new Date().getFullYear())</script> Cloud Chef Labs, Inc. All rights reserved.